#!/usr/bin/env bash
# refresh-cloudflare-ips.sh
#
# Pulls the current Cloudflare IP ranges from cloudflare.com/ips-v4 and -v6
# and writes two nginx include files:
#
#   /etc/nginx/conf.d/cloudflare-ips.conf      — set_real_ip_from directives
#   /etc/nginx/conf.d/cloudflare-ranges.conf   — geo map for the is_cloudflare check
#
# Run as root. Installed as a nightly cron job by the setup scripts.
# Manually: sudo bash deploy/iceland/refresh-cloudflare-ips.sh

set -euo pipefail

if [ "$(id -u)" -ne 0 ]; then
  echo "Must run as root." >&2
  exit 1
fi

TMP_V4=$(mktemp)
TMP_V6=$(mktemp)
trap 'rm -f "$TMP_V4" "$TMP_V6"' EXIT

curl -fsS --max-time 10 https://www.cloudflare.com/ips-v4 > "$TMP_V4"
curl -fsS --max-time 10 https://www.cloudflare.com/ips-v6 > "$TMP_V6"

if ! grep -q '^[0-9]' "$TMP_V4"; then
  echo "ips-v4 fetch returned no IPv4 addresses — aborting" >&2
  exit 1
fi

# Write both files to /etc/nginx/ root (NOT /etc/nginx/conf.d/, which
# nginx auto-loads at http context). cloudflare-ranges.conf contains
# `<cidr> 1;` lines that are only valid inside a geo{} block — if it
# got auto-loaded as a top-level directive, nginx fails to start.
# We include both files explicitly from the site config instead.

# 1. set_real_ip_from directives — nginx trusts these to set the real client IP
{
  echo "# Auto-generated by refresh-cloudflare-ips.sh. Do not edit by hand."
  echo "# Source: https://www.cloudflare.com/ips/"
  echo "# Generated: $(date -u +%FT%TZ)"
  while read -r cidr; do
    [ -z "$cidr" ] && continue
    echo "set_real_ip_from $cidr;"
  done < "$TMP_V4"
  while read -r cidr; do
    [ -z "$cidr" ] && continue
    echo "set_real_ip_from $cidr;"
  done < "$TMP_V6"
} > /etc/nginx/cloudflare-ips.conf

# 2. geo map — sets $is_cloudflare = 1 for any CF range, 0 otherwise
{
  echo "# Auto-generated by refresh-cloudflare-ips.sh. Do not edit by hand."
  while read -r cidr; do
    [ -z "$cidr" ] && continue
    echo "$cidr 1;"
  done < "$TMP_V4"
  while read -r cidr; do
    [ -z "$cidr" ] && continue
    echo "$cidr 1;"
  done < "$TMP_V6"
} > /etc/nginx/cloudflare-ranges.conf

# Clean up legacy paths if a previous broken run left them in conf.d
rm -f /etc/nginx/conf.d/cloudflare-ips.conf /etc/nginx/conf.d/cloudflare-ranges.conf

# Reload nginx if it's running
if systemctl is-active --quiet nginx; then
  nginx -t && systemctl reload nginx
fi

# Install/refresh cron entry
CRON_FILE=/etc/cron.d/refresh-cloudflare-ips
SCRIPT_PATH="$(readlink -f "$0")"
cat > "$CRON_FILE" <<EOF
# Refresh Cloudflare IP ranges nightly at 04:17 UTC
17 4 * * * root $SCRIPT_PATH >> /var/log/cloudflare-ips.log 2>&1
EOF
chmod 644 "$CRON_FILE"

echo "==> Cloudflare IP ranges refreshed."
echo "    IPv4 ranges: $(wc -l < "$TMP_V4")"
echo "    IPv6 ranges: $(wc -l < "$TMP_V6")"
